# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dmitrii/Documents/icp_project/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dmitrii/Documents/icp_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dmitrii/Documents/icp_project/CMakeFiles /home/dmitrii/Documents/icp_project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dmitrii/Documents/icp_project/CMakeFiles 0
.PHONY : all

# # The main clean target
# clean:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
# .PHONY : clean

# # The main clean target
# clean/fast: clean
# .PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named icp_project

# Build rule for target.
icp_project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 icp_project
.PHONY : icp_project

# fast build rule for target.
icp_project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/build
.PHONY : icp_project/fast

#=============================================================================
# Target rules for targets named icp_project_autogen

# Build rule for target.
icp_project_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 icp_project_autogen
.PHONY : icp_project_autogen

# fast build rule for target.
icp_project_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project_autogen.dir/build.make CMakeFiles/icp_project_autogen.dir/build
.PHONY : icp_project_autogen/fast

Controller/GameController.o: Controller/GameController.cpp.o
.PHONY : Controller/GameController.o

# target to build an object file
Controller/GameController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/Controller/GameController.cpp.o
.PHONY : Controller/GameController.cpp.o

Controller/GameController.i: Controller/GameController.cpp.i
.PHONY : Controller/GameController.i

# target to preprocess a source file
Controller/GameController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/Controller/GameController.cpp.i
.PHONY : Controller/GameController.cpp.i

Controller/GameController.s: Controller/GameController.cpp.s
.PHONY : Controller/GameController.s

# target to generate assembly for a file
Controller/GameController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/Controller/GameController.cpp.s
.PHONY : Controller/GameController.cpp.s

Controller/InterfaceController.o: Controller/InterfaceController.cpp.o
.PHONY : Controller/InterfaceController.o

# target to build an object file
Controller/InterfaceController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/Controller/InterfaceController.cpp.o
.PHONY : Controller/InterfaceController.cpp.o

Controller/InterfaceController.i: Controller/InterfaceController.cpp.i
.PHONY : Controller/InterfaceController.i

# target to preprocess a source file
Controller/InterfaceController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/Controller/InterfaceController.cpp.i
.PHONY : Controller/InterfaceController.cpp.i

Controller/InterfaceController.s: Controller/InterfaceController.cpp.s
.PHONY : Controller/InterfaceController.s

# target to generate assembly for a file
Controller/InterfaceController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/Controller/InterfaceController.cpp.s
.PHONY : Controller/InterfaceController.cpp.s

Model/CharacterModel.o: Model/CharacterModel.cpp.o
.PHONY : Model/CharacterModel.o

# target to build an object file
Model/CharacterModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/Model/CharacterModel.cpp.o
.PHONY : Model/CharacterModel.cpp.o

Model/CharacterModel.i: Model/CharacterModel.cpp.i
.PHONY : Model/CharacterModel.i

# target to preprocess a source file
Model/CharacterModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/Model/CharacterModel.cpp.i
.PHONY : Model/CharacterModel.cpp.i

Model/CharacterModel.s: Model/CharacterModel.cpp.s
.PHONY : Model/CharacterModel.s

# target to generate assembly for a file
Model/CharacterModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/Model/CharacterModel.cpp.s
.PHONY : Model/CharacterModel.cpp.s

Model/GameModel.o: Model/GameModel.cpp.o
.PHONY : Model/GameModel.o

# target to build an object file
Model/GameModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/Model/GameModel.cpp.o
.PHONY : Model/GameModel.cpp.o

Model/GameModel.i: Model/GameModel.cpp.i
.PHONY : Model/GameModel.i

# target to preprocess a source file
Model/GameModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/Model/GameModel.cpp.i
.PHONY : Model/GameModel.cpp.i

Model/GameModel.s: Model/GameModel.cpp.s
.PHONY : Model/GameModel.s

# target to generate assembly for a file
Model/GameModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/Model/GameModel.cpp.s
.PHONY : Model/GameModel.cpp.s

Model/MapModel.o: Model/MapModel.cpp.o
.PHONY : Model/MapModel.o

# target to build an object file
Model/MapModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/Model/MapModel.cpp.o
.PHONY : Model/MapModel.cpp.o

Model/MapModel.i: Model/MapModel.cpp.i
.PHONY : Model/MapModel.i

# target to preprocess a source file
Model/MapModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/Model/MapModel.cpp.i
.PHONY : Model/MapModel.cpp.i

Model/MapModel.s: Model/MapModel.cpp.s
.PHONY : Model/MapModel.s

# target to generate assembly for a file
Model/MapModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/Model/MapModel.cpp.s
.PHONY : Model/MapModel.cpp.s

View/mainwindow.o: View/mainwindow.cpp.o
.PHONY : View/mainwindow.o

# target to build an object file
View/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/View/mainwindow.cpp.o
.PHONY : View/mainwindow.cpp.o

View/mainwindow.i: View/mainwindow.cpp.i
.PHONY : View/mainwindow.i

# target to preprocess a source file
View/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/View/mainwindow.cpp.i
.PHONY : View/mainwindow.cpp.i

View/mainwindow.s: View/mainwindow.cpp.s
.PHONY : View/mainwindow.s

# target to generate assembly for a file
View/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/View/mainwindow.cpp.s
.PHONY : View/mainwindow.cpp.s

icp_project_autogen/mocs_compilation.o: icp_project_autogen/mocs_compilation.cpp.o
.PHONY : icp_project_autogen/mocs_compilation.o

# target to build an object file
icp_project_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/icp_project_autogen/mocs_compilation.cpp.o
.PHONY : icp_project_autogen/mocs_compilation.cpp.o

icp_project_autogen/mocs_compilation.i: icp_project_autogen/mocs_compilation.cpp.i
.PHONY : icp_project_autogen/mocs_compilation.i

# target to preprocess a source file
icp_project_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/icp_project_autogen/mocs_compilation.cpp.i
.PHONY : icp_project_autogen/mocs_compilation.cpp.i

icp_project_autogen/mocs_compilation.s: icp_project_autogen/mocs_compilation.cpp.s
.PHONY : icp_project_autogen/mocs_compilation.s

# target to generate assembly for a file
icp_project_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/icp_project_autogen/mocs_compilation.cpp.s
.PHONY : icp_project_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/icp_project.dir/build.make CMakeFiles/icp_project.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... icp_project_autogen"
	@echo "... icp_project"
	@echo "... Controller/GameController.o"
	@echo "... Controller/GameController.i"
	@echo "... Controller/GameController.s"
	@echo "... Controller/InterfaceController.o"
	@echo "... Controller/InterfaceController.i"
	@echo "... Controller/InterfaceController.s"
	@echo "... Model/CharacterModel.o"
	@echo "... Model/CharacterModel.i"
	@echo "... Model/CharacterModel.s"
	@echo "... Model/GameModel.o"
	@echo "... Model/GameModel.i"
	@echo "... Model/GameModel.s"
	@echo "... Model/MapModel.o"
	@echo "... Model/MapModel.i"
	@echo "... Model/MapModel.s"
	@echo "... View/mainwindow.o"
	@echo "... View/mainwindow.i"
	@echo "... View/mainwindow.s"
	@echo "... icp_project_autogen/mocs_compilation.o"
	@echo "... icp_project_autogen/mocs_compilation.i"
	@echo "... icp_project_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

#=============================================================================
# Our custom calls
clean:
	rm -rf cmake_install.cmake CMakeCache.txt CMakeFiles icp_project_autogen icp_project
	@echo "All clean"
pack:
	@echo "Making archive..."
	zip -r xname01-xivanu00.zip *
	@echo "Ready"